### ISSUE TITLE
Font issue for some of the languages

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#42]
The font used for some languages (Czech, polish, bulgarian etc) has to be changed - see graphic design guidelines in Dropbox
https://www.dropbox.com/s/9dbcypjtkqz440s/SpaceA_Visual_Identity_Guide_V1.pdf?dl=0

**Comment by slowe** [comment]
Only Polish, Bulgarian and Greek are specified in that PDF. Should Czech be the same font as for Polish and Bulgarian?

**Comment by slowe** [comment]
The required fonts are Blogger Sans and BPReplay Regular. I have found some web versions of these. If you have an official set, please send them to me. 

I have set the website to use the specified fonts for Polish and Greek. We do not yet have Bulgarian. I need advice on what font to use for Czech.

**Comment by Korczynska** [comment]
Could you please ask Rafa about this?

**Comment by slowe** [comment]
I don't have any contact details for Rafa.

**Comment by unawe** [comment]
Here you go: rafamonterde@yahoo.com <rafamonterde@yahoo.com>


Tibisay Sankatsing Nava
Project Manager Universe Awareness <http://www.unawe.org>
Leiden University

**Comment by slowe** [comment]
Tibisay, thanks for that. I've deleted your comment because this is a public place.

**Comment by slowe** [comment]
This is related to issue #16

**Comment by slowe** [comment]
Rafa says:
* BPReplay supports Greek
* Blogger Sans supports Polish, Bulgarian and Czech

In the German version the main section titles break the design. Rafa said "The only thing that we can do is to ask for a “better” and more short and direct translation." Could someone ask for a shorter translation, specifically for "Berufliche Perspektiven" (Careers).
![screen shot 2016-11-16 at 14 19 27](https://cloud.githubusercontent.com/assets/299787/20350672/b71e9bfc-ac07-11e6-9442-b7c69e6b0283.png)

**Comment by slowe** [comment]
@jorgegrivero Did anyone ask the German translator to shorten the main menu items to stop them breaking the design on narrower screens?

**Comment by vehrlich** [comment]
I found that font 'Miso' is used in slogan. Second one is mentioned 'BloggerSans',
So I want to ask if 'Miso' font should be used on page or I can completely remove it from css.

BloggerSans:
![blg](https://cloud.githubusercontent.com/assets/1701829/21805356/0b45c956-d734-11e6-9e8b-297882bab9ea.png)

Miso:
![miso](https://cloud.githubusercontent.com/assets/1701829/21805368/18cae228-d734-11e6-9ac2-a7c187ae33ad.png)

**Comment by jorgegrivero** [comment]
Hi Vaclav, is not the new font for those languages too big?

Compare frontpage from English to Czech or Polish.

**Comment by jorgegrivero** [comment]
It also happens for Greek, see the section titles for this page  http://www.space-awareness.org/el/games/cerberus/ in comparison with http://www.space-awareness.org/es/games/cerberus/

**Comment by vehrlich** [comment]
@jorgegrivero html inspector shows that both has same font-size (36px) but you're right - one is bigger than second. I'll try to change it.

**Comment by vehrlich** [comment]
Height of font is the same. What is different is weight of each letter, spacing and font itself.
So I player with  css's transform and scale attributes for text under logo to get something similar. But it will newer be the same. Because it is different font.
Bolder letters were bolder than letters in English text.

You have to decide if it is better now :)

Original Czech
![s0](https://cloud.githubusercontent.com/assets/1701829/22312893/40e816c2-e35a-11e6-90fa-91eac95f1a88.png)

Modified Czech
![sa1](https://cloud.githubusercontent.com/assets/1701829/22312906/56e83254-e35a-11e6-822a-89331b337881.png)

Original English
![sa2](https://cloud.githubusercontent.com/assets/1701829/22312915/5d4a9f7e-e35a-11e6-928e-f57770f42d28.png)

Bolder modified Czech
![s4](https://cloud.githubusercontent.com/assets/1701829/22312985/a4734fc2-e35a-11e6-97fa-a6600f092dd7.png)
