### ISSUE TITLE
Other issues with PDF versions of the activities 

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#56]
- The PDF versions of the resources do not mention the authors.

- Hyperlinks are removed in PDF version.

**Comment by slowe** [comment]
As in other issues (#55, #50, #43, #33) I am stuck because I do not understand how the server is rendering the PDFs. I have had a look and tried changing things but with little effect. It may be tha the server is doing some kind of caching which makes it appear as though my changes have not worked or it may be that my changes have not worked. I need help to understand the PDF generation.

**Comment by vehrlich** [comment]
hyperlinks should be working

@jorgegrivero where should be authors placed ? on the first page ?
