### ISSUE TITLE
Problems layout when new interviews are published

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#60]
The way new interviews appear on the website (http://www.space-awareness.org/en/careers/) is different from previously published interviews

This is how it looked 

![interview_page_example](https://cloud.githubusercontent.com/assets/23382266/20880049/a40af690-bad6-11e6-8bea-44c4b6d63917.png)

And this is how it looks when adding new interviews

![interview_page_issue](https://cloud.githubusercontent.com/assets/23382266/20880076/ba3a664e-bad6-11e6-9ea5-b8e7f8f2edbd.png)

**Comment by slowe** [comment]
@jorgegrivero Thanks for the screenshots.

The problem is this specific interview not new interviews in general. This interview appears in this manner due to the lack of non-floating content in the left column. The green boxes have to "float" so that we can deal with narrow screens (having three in a row wouldn't fit so we need to be able to dynamically change the number per row). The only "non-floated" content is the text ("Jorge Vago is the 2020 Exomars mission Project Scientist"). Basically, the sentence in the mini-profile is too short so it doesn't force the column to be the width it is supposed to be (75%). The previous interviews all have sentences that fill the column width so don't show the problem. The problem will be solved when a long enough paragraph is added. However, I've been able to tweak the CSS to 'fix' this.
