### ISSUE TITLE
Link interviews on Careers Profiles

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#97]
On the Career Section, for some of the Career profiles (http://www.space-awareness.org/en/careers/career/what-astrochemist/ for example), there is an option on the right hand column to go to a related interview that so far is not working. Could you activate the link please please?

**Comment by vehrlich** [comment]
@jorgegrivero problem is there is no link.
If you see to the administration of  [carreer](http://www.space-awareness.org/admin/careers/career/2/?language=en) there is no connection to interview. There is only simple text that tells name of scientist.

So there are two options:
* update only template with link to interview. Because there is only name which connects career and interview - there must be match in those names (especially in slug names). So slugname from [interview](http://www.space-awareness.org/admin/careers/interview/8/?language=en) must be the same slug which will be created from [carreer](http://www.space-awareness.org/admin/careers/career/2/?language=en) Interview field value (it means change 'Meet Anita ...' to 'Dr Anita ...')

* update model info. Then Interview field from [carreer](http://www.space-awareness.org/admin/careers/career/2/?language=en) will not be only text, it will point to specific Interview.

First option is easy. It needs just have same names to match and some changes in template.
Second is more clean but it takes more time.

Now it depends how awesome you want to have it :)

**Comment by vehrlich** [comment]
@jorgegrivero  Ok, I'm sorry. First option will not be possible, because Interview text value is language dependant ... So I'll connect models.

**Comment by vehrlich** [comment]
Now can be any career added to each interview. http://www.space-awareness.org/admin/careers/interview/
Then links to interviews connected with careers are shown in career detail.
